-- DropForeignKey
ALTER TABLE "FAC_PRODUCTO" DROP CONSTRAINT "FAC_PRODUCTO_factura_fk_fkey";

-- AddForeignKey
ALTER TABLE "FAC_PRODUCTO" ADD CONSTRAINT "FAC_PRODUCTO_factura_fk_fkey" FOREIGN KEY ("factura_fk") REFERENCES "FACTURA"("factura_pk") ON DELETE CASCADE ON UPDATE CASCADE;
