-- DropForeignKey
ALTER TABLE "CARRITO_ITEM" DROP CONSTRAINT "CARRITO_ITEM_producto_fk_fkey";

-- DropForeignKey
ALTER TABLE "FAC_PRODUCTO" DROP CONSTRAINT "FAC_PRODUCTO_producto_fk_fkey";

-- DropForeignKey
ALTER TABLE "IMAGEN" DROP CONSTRAINT "IMAGEN_producto_fk_fkey";

-- DropForeignKey
ALTER TABLE "INVENTARIO" DROP CONSTRAINT "INVENTARIO_producto_fk_fkey";

-- DropForeignKey
ALTER TABLE "REGISTRO" DROP CONSTRAINT "REGISTRO_producto_fk_fkey";

-- AddForeignKey
ALTER TABLE "CARRITO_ITEM" ADD CONSTRAINT "CARRITO_ITEM_producto_fk_fkey" FOREIGN KEY ("producto_fk") REFERENCES "PRODUCTOS"("producto_pk") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "IMAGEN" ADD CONSTRAINT "IMAGEN_producto_fk_fkey" FOREIGN KEY ("producto_fk") REFERENCES "PRODUCTOS"("producto_pk") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INVENTARIO" ADD CONSTRAINT "INVENTARIO_producto_fk_fkey" FOREIGN KEY ("producto_fk") REFERENCES "PRODUCTOS"("producto_pk") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REGISTRO" ADD CONSTRAINT "REGISTRO_producto_fk_fkey" FOREIGN KEY ("producto_fk") REFERENCES "PRODUCTOS"("producto_pk") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FAC_PRODUCTO" ADD CONSTRAINT "FAC_PRODUCTO_producto_fk_fkey" FOREIGN KEY ("producto_fk") REFERENCES "PRODUCTOS"("producto_pk") ON DELETE CASCADE ON UPDATE CASCADE;
