-- AlterTable
ALTER TABLE "CARRITO_ITEM" ADD COLUMN     "talla_fk" INTEGER;

-- AddForeignKey
ALTER TABLE "CARRITO_ITEM" ADD CONSTRAINT "CARRITO_ITEM_talla_fk_fkey" FOREIGN KEY ("talla_fk") REFERENCES "TALLA"("talla_pk") ON DELETE SET NULL ON UPDATE CASCADE;
